remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
title: A Semester of Digital Humanities
description: This website documents the work of Sukya Williams during the Fall 24 Semester of the Digital Humanities course at the University of Pennsylvania
